import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import GooeyCursor from "@/components/GooeyCursor";
import localFont from "next/font/local";
import Footer from "@/components/Footer";
import Header from "@/components/Header";

// const inter = Inter({ subsets: ["latin"] });
const favoritFont = localFont({
  src: "./FavoritFont.otf",
  variable: "--FavoritFont",
});
const cyberthrone = localFont({
  src: "./Cyberthrone.ttf",
  variable: "--Cyberthrone",
});

const trailers = localFont({
  src: "./Trailers.ttf",
  variable: "--Trailers",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${favoritFont.variable} ${cyberthrone.variable}  ${trailers.variable} `}>
        <GooeyCursor />
        <Header />

        {children}
        <Footer />
      </body>
    </html>
  );
}
